// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "DailyStack – Your Daily Dose of Tech Updates",
    "description": "Stay up to date with the latest technology news, tutorials, tools, and industry insights. Freshly curated for developers and tech enthusiasts."
  },
  "Header": {
    "link1": "Home",
    "link2": "Articles",
    "link3": "Close"
  },
  "Hero": {
    "welcome": "Your daily gateway to the tech world.",
    "description1": "Explore the latest articles, trends, and insights in technology.",
    "description2": "Stay informed with clean summaries, deep dives, and curated content.",
    "action": "Start Reading"
  },
  "About": {
    "badge1": "Curated",
    "description1": "We gather high-quality tech articles from trusted sources.",
    "badge2": "Practical",
    "description2": "Stay informed without information overload thanks to clean summaries.",
    "badge3": "Customizable",
    "description3": "Choose your topics, set your preferences, and read what matters to you."
  },
  "Methods": {
    "title": "Tech news, refined. Just the way it should be.",
    "step1": {
      "title": "Personalize your feed",
      "description": "Pick your favorite technologies and let DailyStack tailor your experience."
    },
    "step2": {
      "title": "Read from trusted sources",
      "description": "We aggregate articles from reputable blogs, companies, and industry experts."
    },
    "step3": {
      "title": "Get streamlined updates",
      "description": "Receive summaries, alerts, and weekly digests directly to your inbox."
    }
  },
  "Action": {
    "title": "Ready to stay ahead in tech?",
    "button": "Explore Articles"
  },
  "Footer": {
    "items": {
      "terms": "Terms of Service",
      "privacy": "Privacy Policy"
    }
  },
  "ArticlesPage": {
    "Metadata": "Discover our Recent Articles | DailyStack",
    "title": "Recent Articles",
    "placeholder": "Search articles..."
  },
  "loader": {
    "loadingArticles": "Loading articles...",
    "loadingArticle": "Loading article..."
  },
  "error": {
    "message": "Something went wrong!",
    "retry": "Please try again."
  },
  "Legal": {
    "termsTitle": "Terms of Service | DailyStack",
    "privacyTitle": "Privacy Policy | DailyStack",
    "lastUpdated": "Last Updated:",
    "siteName": "DailyStack",
    "contactEmail": "yukiarnold56@gmail.com",

    "termsIntro": "Welcome to DailyStack. By accessing or using our website, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, then you may not access the service.",
    "termsUseHeading": "1. Use License",
    "termsUseText": "Permission is granted to temporarily download one copy of the materials (information or software) on DailyStack's website for personal, non-commercial transitory viewing only. This is the grant of a license, not a transfer of title.",
    "termsDisclaimerHeading": "2. Disclaimer",
    "termsDisclaimerText": "The materials on DailyStack's website are provided on an 'as is' basis. DailyStack makes no warranties, expressed or implied, and hereby disclaims all other warranties including, without limitation, implied warranties of merchantability, fitness for a particular purpose, or non-infringement.",

    "privacyIntro": "Your privacy is important to us. This Privacy Policy describes how DailyStack collects, uses, and discloses your personal information when you visit or use our Service.",
    "privacyDataHeading": "1. Data We Collect",
    "privacyDataText": "We collect information you directly provide us, such as your email address if you subscribe to a newsletter. We also automatically collect non-personal data like IP address, browser type, and pages visited, using tools like Google Analytics.",
    "privacyUseHeading": "2. How We Use Your Data",
    "privacyUseText": "The collected information is used for providing and maintaining the Service, improving the Service, understanding how our Service is used, and communicating with you (e.g., sending updates or newsletters).",
    "privacyCookiesHeading": "3. Cookies",
    "privacyCookiesText": "We use 'cookies' to collect information and track activity on our Service. You can instruct your browser to refuse all cookies or to indicate when a cookie is being sent."
  }
};
export default messages;