// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "DailyStack - Votre veille technologique quotidienne",
    "description": "Découvrez chaque jour les derniers articles, nouveautés tech, tendances IA, frameworks et outils essentiels. Résumés intelligents, filtres, recherche et notifications email."
  },
  "Header": {
    "link1": "Accueil",
    "link2": "Articles",
    "link3": "Fermer"
  },
  "Hero": {
    "welcome": "Votre dose quotidienne d'actualité tech.",
    "description1": "Accédez aux dernières tendances en IA, développement web, frameworks et outils.",
    "description2": "Lisez des résumés clairs générés par l’IA et ne ratez plus aucune nouveauté.",
    "action": "Explorer les articles"
  },
  "About": {
    "badge1": "Simple",
    "description1": "Une interface claire pour suivre toutes les actualités technologiques au même endroit.",
    "badge2": "Efficace",
    "description2": "Des résumés générés par l’IA pour comprendre rapidement l’essentiel de chaque article.",
    "badge3": "Personnalisable",
    "description3": "Filtres, thèmes, langues — adaptez DailyStack à votre façon de lire."
  },
  "Methods": {
    "title": "Votre veille technologique, simplifiée.",
    "step1": {
      "title": "Filtrez selon vos centres d'intérêt",
      "description": "Que vous soyez passionné d’IA, de React, de Next.js ou de cybersécurité, trouvez rapidement ce qui vous intéresse."
    },
    "step2": {
      "title": "Recevez des résumés IA",
      "description": "Chaque article est résumé pour vous offrir une compréhension rapide et complète du contenu important."
    },
    "step3": {
      "title": "Restez toujours informé",
      "description": "Activez les notifications email pour recevoir les nouveautés dès qu'elles sortent."
    }
  },
  "Action": {
    "title": "Prêt à optimiser votre veille technologique ?",
    "button": "Découvrir DailyStack"
  },
  "Footer": {
    "items": {
      "terms": "Conditions d'utilisation",
      "privacy": "Politique de confidentialité"
    }
  },
  "ArticlesPage": {
    "Metadata": "Découvrez nos Articles Récents | DailyStack",
    "title": "Articles Récents",
    "placeholder": "Recherche..."
  },
  "loader": {
    "loadingArticles": "Chargement des articles...",
    "loadingArticle": "Chargement de l'article..."
  },
  "error": {
    "message": "Une erreur est survenue !",
    "retry": "Veuillez réessayer."
  },
  "Legal": {
    "termsTitle": "Conditions d'Utilisation | DailyStack",
    "privacyTitle": "Politique de Confidentialité | DailyStack",
    "lastUpdated": "Dernière mise à jour :",
    "siteName": "DailyStack",
    "contactEmail": "contact@dailystack.com",

    "termsIntro": "Bienvenue sur DailyStack. En accédant à notre site ou en l'utilisant, vous acceptez d'être lié par les présentes Conditions d'Utilisation. Si vous n'êtes pas d'accord avec une partie de ces conditions, vous ne pouvez pas accéder au service.",
    "termsUseHeading": "1. Licence d'Utilisation",
    "termsUseText": "L'autorisation est accordée de télécharger temporairement une copie des documents (informations ou logiciels) sur le site web de DailyStack, uniquement pour une visualisation personnelle, non commerciale et transitoire. Ceci est l'octroi d'une licence, et non un transfert de titre.",
    "termsDisclaimerHeading": "2. Clause de Non-responsabilité",
    "termsDisclaimerText": "Les documents sur le site web de DailyStack sont fournis 'tels quels'. DailyStack n'offre aucune garantie, expresse ou implicite, et décline par la présente toute autre garantie, y compris, sans limitation, les garanties implicites de qualité marchande, d'adéquation à un usage particulier ou de non-contrefaçon.",

    "privacyIntro": "Votre vie privée est importante pour nous. Cette Politique de Confidentialité décrit comment DailyStack collecte, utilise et divulgue vos informations personnelles lorsque vous visitez ou utilisez notre Service.",
    "privacyDataHeading": "1. Données que Nous Collectons",
    "privacyDataText": "Nous collectons les informations que vous nous fournissez directement, comme votre adresse e-mail si vous vous abonnez à une newsletter. Nous collectons également automatiquement des données non personnelles comme l'adresse IP, le type de navigateur et les pages visitées, en utilisant des outils comme Google Analytics.",
    "privacyUseHeading": "2. Comment Nous Utilisons Vos Données",
    "privacyUseText": "Les informations collectées sont utilisées pour fournir et maintenir le Service, l'améliorer, comprendre comment notre Service est utilisé, et communiquer avec vous (par exemple, envoyer des mises à jour ou des newsletters).",
    "privacyCookiesHeading": "3. Témoins (Cookies)",
    "privacyCookiesText": "Nous utilisons des 'témoins' (cookies) pour recueillir des informations et suivre l'activité sur notre Service. Vous pouvez demander à votre navigateur de refuser tous les cookies ou d'indiquer quand un cookie est envoyé."
  }
};
export default messages;