// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "Metadata": {
    "title": "DailyStack - Votre veille technologique quotidienne",
    "description": "Découvrez chaque jour les derniers articles, nouveautés tech, tendances IA, frameworks et outils essentiels. Résumés intelligents, filtres, recherche et notifications email."
  },
  "Header": {
    "link1": "Accueil",
    "link2": "Articles"
  },
  "Hero": {
    "welcome": "Votre dose quotidienne d'actualité tech.",
    "description1": "Accédez aux dernières tendances en IA, développement web, frameworks et outils.",
    "description2": "Lisez des résumés clairs générés par l’IA et ne ratez plus aucune nouveauté.",
    "action": "Explorer les articles"
  },
  "About": {
    "badge1": "Simple",
    "description1": "Une interface claire pour suivre toutes les actualités technologiques au même endroit.",
    "badge2": "Efficace",
    "description2": "Des résumés générés par l’IA pour comprendre rapidement l’essentiel de chaque article.",
    "badge3": "Personnalisable",
    "description3": "Filtres, thèmes, langues — adaptez DailyStack à votre façon de lire."
  },
  "Methods": {
    "title": "Votre veille technologique, simplifiée.",
    "step1": {
      "title": "Filtrez selon vos centres d'intérêt",
      "description": "Que vous soyez passionné d’IA, de React, de Next.js ou de cybersécurité, trouvez rapidement ce qui vous intéresse."
    },
    "step2": {
      "title": "Recevez des résumés IA",
      "description": "Chaque article est résumé pour vous offrir une compréhension rapide et complète du contenu important."
    },
    "step3": {
      "title": "Restez toujours informé",
      "description": "Activez les notifications email pour recevoir les nouveautés dès qu'elles sortent."
    }
  },
  "Action": {
    "title": "Prêt à optimiser votre veille technologique ?",
    "button": "Découvrir DailyStack"
  },
  "Footer": {
    "items": {
      "terms": "Conditions d'utilisation",
      "privacy": "Politique de confidentialité",
      "review": "Envoyer un feedback"
    }
  },
  "ArticlesPage": {
    "title": "Articles Récents"
  }
};
export default messages;